### ISSUE TITLE
Registration - Show which field has invalid data

### ISSUE THREAD

**Issue by LaBlazer** [LaBlazer/storrmbox#33]
Currently only notification is shown, there's an error array returned from BE that shows which fields/values are invalid

**Comment by Ed-zo** [comment]
Could you specify the array keys so I can match them to the form fields? Be more specific. Currently added only email in https://github.com/LaBlazer/storrmbox/commit/bbb823af7bbee901c9809a44242e943a990bec5f.

**Comment by LaBlazer** [comment]
Improved in https://github.com/LaBlazer/storrmbox/commit/941654866a0e5d3e00b956db9c00ab3d8b2922e5

**Comment by Ed-zo** [comment]
Improved in https://github.com/LaBlazer/storrmbox/commit/0ee1ed4392d6b504c92b9752e4e1068acdbd2e28. Now every field will show an error if one is returned.
