### ISSUE TITLE
Media can have Runtime N/A

### ISSUE THREAD

**Issue by Ed-zo** [LaBlazer/storrmbox#4]
Error when fetching content. Runtime can have N/A value. Example: imdb_id: tt7949218

![image](https://user-images.githubusercontent.com/15330300/68994642-826bd900-0885-11ea-8c26-55ce897edf83.png)

**Comment by LaBlazer** [comment]
This is an issue with OMDB. The data is present on IMDB but not fetched on OMDB... Maybe we should use https://www.imdb.com/interfaces/ to get the data ourselves?

**Comment by LaBlazer** [comment]
https://github.com/omdbapi/OMDb-API/issues/158

**Comment by josezulu** [comment]
It should return NaN

**Comment by LaBlazer** [comment]
> It should return NaN when unknown.

This is unfortunately not in our control, we are just using the API.

**Comment by josezulu** [comment]
> 
> 
> > It should return NaN when unknown.
> 
> This is unfortunately not in our control, we are just using the API.

You are correct, I'm sorry, the way I responded I meant to say "it should be corrected to return NaN when unknown".

I edited my comment later, for the moment you need to handle it programmatically checking its value before converting it.

**Comment by LaBlazer** [comment]
> It should return NaN when unknown.
> 
> EDIT: you would need to handle that then programmatically. In my case, I just check its value before trying to parse it as a number.

This is unfortunately not in our control, we are just using the API. I know it can be handled programatically but that is not optimal since we are caching the results.

**Comment by LaBlazer** [comment]
Should be fixed by https://github.com/LaBlazer/storrmbox/commit/e3a0861cfe75e18e1c793a740957eb6f02cb4f2c

**Comment by josezulu** [comment]
I thought I was responding to an issue on the "omdbapi" repository. I don't know what "storrmbox" is, nor do I use it. I've removed my comments as they weren't intended for this repository.

**Comment by LaBlazer** [comment]
> I thought I was responding to an issue on the "omdbapi" repository. I don't know what "storrmbox" is, nor do I use it. I've removed my comments as they weren't intended for this repository.

No problem, I thought so :)
