### ISSUE TITLE
Account - Add security page

### ISSUE THREAD

**Issue by LaBlazer** [LaBlazer/storrmbox#44]
Log out of all sessions button, password change, last login time and IP

**Comment by Ed-zo** [comment]
Created in https://github.com/LaBlazer/storrmbox/commit/73482a66f8a5b0b960e2116f34951a6d8fc73d30. Now only need an endpoint for changing the password.

**Comment by Ed-zo** [comment]
Added in https://github.com/LaBlazer/storrmbox/commit/5ed53f9c9346d31ab5113b0fd4567e21ec6561c5 and https://github.com/LaBlazer/storrmbox/commit/aa042a49ebfb450bf078b6420d916d3c4e27e82f
