### ISSUE TITLE
Another N/A value in content

### ISSUE THREAD

**Issue by Ed-zo** [LaBlazer/storrmbox#5]
![image](https://user-images.githubusercontent.com/15330300/68998953-38044f80-08b9-11ea-8cd2-45fcd66297c8.png)

Time has N/A

Imdb id: tt5180504

**Comment by Ed-zo** [comment]
Also "season" can have N/A. Imdb ID: tt8068860

**Comment by LaBlazer** [comment]
Fixed by https://github.com/LaBlazer/storrmbox/commit/8bf2963ce86a7d227e2fd77f5034262d834f3b31
