### ISSUE TITLE
Registration - Email format

### ISSUE THREAD

**Issue by Ed-zo** [LaBlazer/storrmbox#52]
**Description**
Email checking could be improved. Current checking allows to use email in format number@number. 
https://github.com/LaBlazer/storrmbox/blob/941654866a0e5d3e00b956db9c00ab3d8b2922e5/backend/storrmbox/api/user.py#L34

**Expected behavior**
I don't think that is a correct email format.

**Screenshots**

![image](https://user-images.githubusercontent.com/15330300/76303789-94eda080-62c2-11ea-8d7c-e405476857dc.png)

User was registered with no problem

**Comment by LaBlazer** [comment]
This is weird, the check=True parameter should enable DNS checking on all email addresses (https://flask-restplus.readthedocs.io/en/stable/api.html#module-flask_restplus.inputs). I'll look into it...

**Comment by LaBlazer** [comment]
Fixed by https://github.com/LaBlazer/storrmbox/commit/f6dfa5e919dddb4ca6ad373de74c63f010fb9403
