### ISSUE TITLE
Registration - Username or email that is already used not checked

### ISSUE THREAD

**Issue by Ed-zo** [LaBlazer/storrmbox#53]
**Description**
Username and email is unique but is not checked during registration. No error is returned (server probably crashes).

**Expected behavior**
User should get error if the username or email is used.

**Code**
https://github.com/LaBlazer/storrmbox/blob/941654866a0e5d3e00b956db9c00ab3d8b2922e5/backend/storrmbox/api/user.py#L40-L57

**Comment by LaBlazer** [comment]
I already know about this issue, I have a fix ready but I did not test it yet

**Comment by LaBlazer** [comment]
Fixed in https://github.com/LaBlazer/storrmbox/commit/f3512dc71d8f88c359b9f9b3a15312229fc2e653
