### ISSUE TITLE
Moderator/Admin panel

### ISSUE THREAD

**Issue by LaBlazer** [LaBlazer/storrmbox#55]
Add admin panel into account settings that will be shown only to users with permission level larger than 0

**Comment by LaBlazer** [comment]
Added with https://github.com/LaBlazer/storrmbox/commit/ccd716573cf05123e91f12d4c7d3d3a515c7e6a1

**Comment by Ed-zo** [comment]
Closing this for now. If there is anything else that needs to be added to the admin panel reopen this issue.
