### ISSUE TITLE
Align footer to bottom of the page

### ISSUE THREAD

**Issue by LaBlazer** [LaBlazer/storrmbox#57]
```
position: fixed;
bottom: 0;
left: 50%;
transform: translateX(-50%);
```
in footer

**Comment by Ed-zo** [comment]
If this aproach is used, the footer would overlay some components. Is this desirable behaviour / design?

![image](https://user-images.githubusercontent.com/15330300/76461784-d5dbd700-63e0-11ea-8009-c8625797b045.png)

**Comment by Ed-zo** [comment]
Adjusted in https://github.com/LaBlazer/storrmbox/commit/09aa58b66784f32073d9a3e8f1347686539cc78b
