### ISSUE TITLE
InternalException: Invalid movie

### ISSUE THREAD

**Issue by Ed-zo** [LaBlazer/storrmbox#6]
![image](https://user-images.githubusercontent.com/15330300/68999089-ca0d5780-08bb-11ea-897a-b5f1821a99be.png)

Imdb ID: tt11165002

**Comment by LaBlazer** [comment]
Fixed by https://github.com/LaBlazer/storrmbox/commit/8bf2963ce86a7d227e2fd77f5034262d834f3b31
